name: ESLint Check

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          
      - name: Install dependencies
        run: |
          npm ci
          npm install eslint@9 --save-dev
          
      - name: Run ESLint
        run: |
          # Print ESLint version to verify
          npx eslint --version
          
          # Run ESLint with verbose output
          npx eslint component/src --config eslint.config.cjs --format json --ext .js > results.json || exit_code=$?
          
          # If there are lint errors, exit with code 1
          if [ -n "$exit_code" ]; then
            echo "ESLint found issues"
            cat results.json
            exit $exit_code
          fi
                    
      - name: Upload ESLint results
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: eslint-results
          path: results.json